### PR TITLE
iphone_simpath should only print "Using ios-sim at..." message when debugging

### PR DESCRIPTION
**Pull request by jmoody**
Limits the puts statement with $DEBUG

Calabash iOS calls Simulator.new often and each time this message is generated.  

Let me know if you want something fancier.

### CODE REVIEW

**Comment by moredip** [comment]
thanks Joshua

**Comment by moredip** [comment]
If you'd like I'd be happy to give you commit bit here plus rubygems publishing rights so you don't have to coordinate with me every time Calabash needs a tweak

**Comment by jmoody** [comment]
@moredip 

> give you commit bit here plus rubygems publishing rights

Ha!  A blessing and a curse!

Let's start with the git commit privileges.  I will delete my fork and issue pull requests for your review until we comfortable with each other.

Thanks!

jjm

**Comment by jmoody** [comment]
@moredip 

Hi Pete, 

We are going to be releasing a new version soon.  Is there any chance you'd consider releasing
a new version of SimLauncher with this PR?  It would help reduce the console spam for calabash-ios users. 

If you want to familiarize me with the process of releasing the gem, I'm game.

Thanks!

**Comment by moredip** [comment]
Happy to release a new version. I'll work on that now.

**Comment by moredip** [comment]
Pushed 0.4.10 to rubygems. It should show up shortly, if not now.

**Comment by jmoody** [comment]
@moredip Thanks Pete!

@krukow - I have updated the calabash-cucumber gemspec.

**Pull request merged**
