### PR TITLE
xcode-select should use --print-path flag

### PR DESCRIPTION
**Pull request by jmoody**
## motivation

Calabash users are reporting:

```
xcode-select: Error: unknown command option '-p'.
```

I cannot reproduce locally, but it has been reported multiple times.

I have not been able to pin this to a particular version of MacOS, command-line tools, or Xcode.

I am stumped.

I did a grep over ios-sim and calabash for `xcode-select -p` and I believe that sim_launcher is the only place `-p` is used.

### CODE REVIEW

**Comment by pavelbalintef** [comment]
OS X Mountain Lion installed, 
XCode 5.1 
Ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin12.0]
Calabash-ios version 0.9.168

$ xcode-select -p
xcode-select: Error: unknown command option '-p'.

xcode-select: Report or change the path to the active
              Xcode installation for this machine.

Usage: xcode-select --print-path
           Prints the path of the active Xcode folder
   or: xcode-select --switch <xcode_path>
           Sets the path for the active Xcode folder
   or: xcode-select --version
           Prints the version of xcode-select

**Comment by jmoody** [comment]
@pavelbalintef  Thanks for updating the PR

https://groups.google.com/forum/?fromgroups=#!topic/calabash-ios/4bBpRCNObFE

**Comment by jamieforrest** [comment]
+1

**Comment by jamieforrest** [comment]
@jmoody What version of `xcode-select` are you running? I am on:

```
$ xcode-select --version
xcode-select version 2311.
```

**Comment by jmoody** [comment]
@jamieforrest 

```
$ xcode-select --version
xcode-select version 2333
```

Weirdness.

**Comment by jamieforrest** [comment]
Ok just tried reinstalling command line tools from https://developer.apple.com/downloads/index.action#, and I get the same version of `xcode-select` (2311). Are you on Mavericks, @jmoody?

**Comment by jmoody** [comment]
@jamieforrest yuppers.

```
$ sw_vers -productVersion 
10.9.2

$ xcodebuild -version
Xcode 5.1.1
Build version 5B1008
```

**Comment by jamieforrest** [comment]
```
$ sw_vers -productVersion
10.8.5
$ xcodebuild -version
Xcode 5.1.1
Build version 5B1008
```

**Comment by jmoody** [comment]
So it is actually a Mountain Lion issue?  Wacky.

**Comment by jamieforrest** [comment]
Or, more specifically, version 2311 of `xcode-select`? Perhaps?

**Comment by jamieforrest** [comment]
@jmoody Does your version (2333) of `xcode-select` support the `-p` option?

**Comment by jmoody** [comment]
@jamieforrest  yes. :(

**Comment by jamieforrest** [comment]
@moredip Please see the conversation above. It seems the only workaround is this PR.

**Comment by moredip** [comment]
Fun stuff. Thanks for putting the leg work in to figure this weirdness out

**Comment by jamieforrest** [comment]
@moredip Thanks for the merge. Any chance we can get this into a tag fairly soon? Calabash needs to be able to depend on an updated gem in order to fix this issue on their end. cc @jmoody

**Comment by jmoody** [comment]
@moredip We are nearly ready to make our 0.9.169 release.  I hate to ask again for a release so soon after my last request, but would you mind?  Alternatively, you could email me the instructions for releasing and I will make a patch release.

Thanks!

**Comment by moredip** [comment]
Done. 0.4.11 has this change. FYI I'm also going to take some time now to _finally_ get #16 landed.

**Pull request merged**
