### PR TITLE
Topic/ios8 support

### PR DESCRIPTION
**Pull request by faisalmemon**
I am totally new to this code repo, and came to it whilst trying to get started with frank automated testing.  I am on ios8 and saw that ios-sim will abort unless the newer version of it is bundled.  The phone gap version seems most recently maintained so I decided to bring that in as a submodule and deployed it into the system.

I hope these changes are of help to you, but if you want to do it differently or decide a better route, I would be interested in how you progress ios8 support.

Cheers,
faz.

### CODE REVIEW

**Comment by dlprows** [comment]
If you're interested in knowing this, I took a look at the deep down code to run the ios-sim executable. It looks like if you have ios-sim on your path (install using the readme in phonegap's official repo) then it'll use the installed version instead of the bundled version.
I personally think that the bundled version should just go away and a readme should be added to this repo telling people to install from the official repo

**Comment by moredip** [comment]
Agreed. 

Any chance you could add that change to the README as you suggested? I'd be happy to pull in the change. 

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by crishoj** [comment]
I've sent @faisalmemon a pull request with a README: faisalmemon/Sim-Launcher#1
Also clears out the binary `ios-sim` from the gem.

**Comment by faisalmemon** [comment]
Changes from crishoj are good.  Tested locally.  Much appreciated.

**Comment by faisalmemon** [comment]
moredip -- can you evaluate this pull request please, since crishoj has done your suggestions, which I've merged.  If I've forgotten to tick a box, or am doing something wrong at my end let me know (in case you are waiting on me to do something).  Best regards, faisalmemon.

**Comment by moredip** [comment]
Thanks a lot for doing the work. I'll push a new version of the gem now.

**Comment by moredip** [comment]
released as 0.4.12. Thanks again.

**Pull request merged**
