### PR TITLE
support for starting and resetting (updated ios-sim dep)

### PR DESCRIPTION
**Pull request by krukow**
Support for starting simulator without launch 
(new ios-sim gem: 
https://github.com/calabash/ios-sim/commit/84e2070bd952a8011cbfee4347e2d3a09b7d73bb
).

Support for resetting simulator via applescript.

Example

krukow:~/github/Sim-Launcher$ rake install
sim_launcher 0.4.7 built to pkg/sim_launcher-0.4.7.gem
sim_launcher (0.4.7) installed
krukow:~/github/Sim-Launcher$ irb
irb(main):001:0> require 'sim_launcher'
=> true
irb(main):002:0> l=SimLauncher::Simulator.new
=> #<SimLauncher::Simulator:0x007fd9e1adba70 @iphonesim_path="/Users/krukow/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sim_launcher-0.4.7/lib/sim_launcher/../../native/ios-sim">
irb(main):003:0> l.reset
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
=> ""
irb(main):004:0> l.reset ["6.0"]
«class butT» Reset of window 1 of «class pcap» iPhone Simulator
«class butT» Reset of window 1 of «class pcap» iPhone Simulator

### CODE REVIEW

**Comment by moredip** [comment]
This looks good Karl. One thing I'm not stoked about is the binary applescript file. Makes it tricky to do diffs, etc. Would you be able to put the script inline in simulator.rb, or to include it as a plaintext file and then read it in an evaluate it with `osascript`?

**Comment by krukow** [comment]
Sure will do.

**Comment by krukow** [comment]
https://github.com/calabash/Sim-Launcher/commit/66d625d75a5e632db8e1d31d2bc3c379c1da8ed7

**Comment by krukow** [comment]
And this commit uses the plaintext version:

https://github.com/calabash/Sim-Launcher/commit/24c284a4374fd66c190aab474b313163b93cac7d

**Comment by krukow** [comment]
Would you have time to merge this one and perhaps cut a release?

Cheers,
- Karl

**Comment by moredip** [comment]
Sorry, this pull request got lost between the cracks :(

Can you rebase/merge on top of master? It doesn't cleanly merge now due to me pulling in another pull request.

**Pull request closed without merging**
